### ISSUE TITLE
Aktueller Hausverbrauch

### ISSUE THREAD

**Issue by Tscherno** [netzkind/telegraf-kostal-modbus#1]
Danke erstmal für das Veröffentlichen deiner Arbeit! Ich kannte Telegraf und die Möglichkeit so direkt von Modbus Daten nach InfluxDB zu schaufeln noch gar nicht. Ich war gerade dabei es per Node Red zu lösen, aber die Variante mit eigenem Docker Image das genau das macht und sonst nichts gefällt mir besser.

Nun meine Frage: Wenn ich es richtig verstehe, sollte im Register "Total home consumption" der aktuelle Hausverbrauch stehen, oder? Ich kriege damit nur unplausible Werte angezeigt, sieht eher so aus als ob ich einen Zeitraum sehe. Ich muss zugeben, dass ich mit Grafana bzw. InfluxDB auch noch nicht so viel gemacht habe... Vielleicht kannst Du mir einen Tipp geben, wie ich einfach einen Wert bekomme, nämlich den letzten gemeldeten Hausverbrauch (unabhängig über welche Quelle gemeldet).

**Comment by netzkind** [comment]
"Total home consumption" sollte den gesamten Verbrauch seit Installation der Wallbox enthalten. Der Wert ist also eine Summe in kWh. 
Wenn du den Verbrauch für einen Zeitraum haben willst musst du also die Differenz bilden aus "Wert zu Beginn" und "Wert zum Ende" des Zeitraums. In InfluxDB kannst du dafür die Funktion "difference()" verwenden.

**Comment by Tscherno** [comment]
OK, dann habe ich den Wert schon mal falsch verstanden. Ich will den Verbrauch gar nicht für einen Zeitraum anzeigen, sondern den momentan Ist-Wert. Eigentlich genau das was der Wechselrichter auf seinem Webinterface anzeigt:
![grafik](https://user-images.githubusercontent.com/5594674/72217192-7326a600-352b-11ea-8add-625a35c07ee0.png)

**Comment by netzkind** [comment]
Das gibt es nicht als Einzelwert. Hier muss stattdessen die Summe aus "Home own consumption from grid", "Home own consumption from PV" und "Home own consumption from battery" gebildet und verwendet werden.
